// Relationshape questionnaire data model.
// Source: Relationshape Pre-Release 1 (Anne Lüscher, Benjamin Frey, 2025)
// Licensed CC BY-NC 4.0. Adapted for app use.

// Default scale, lowest disagreement first, strongest agreement last.
// Numeric values are derived from position automatically.
// Users can customise labels / colours / step count via Map settings.
export const DEFAULT_SCALE = [
  { key: "no",         label: "No",            short: "No",         value: 0, color: "#264653", description: "I do not want / agree to this." },
  { key: "not-really", label: "Not really",    short: "Not really", value: 1, color: "#577590", description: "I lean against this." },
  { key: "maybe",      label: "Maybe / future",short: "Maybe",      value: 2, color: "#43aa8b", description: "Hopefully or maybe in the future." },
  { key: "open",       label: "Open to it",    short: "Open",       value: 3, color: "#90be6d", description: "I am open, neutral, willing to explore." },
  { key: "want",       label: "Want / like",   short: "Want",       value: 4, color: "#f9c74f", description: "I would like this." },
  { key: "hell-yes",   label: "Hell, yes!",    short: "Hell yes",   value: 5, color: "#f3722c", description: "Strong yes, exciting and welcome." },
  { key: "need",       label: "Need",          short: "Need",       value: 6, color: "#e63946", description: "Highest importance. If unmet I may reconsider the relationship." },
];

// Tag GR = item supports giving/receiving notation.
// Categories trimmed slightly for app use; users can add custom items in profile.
export const CATEGORIES = [
  {
    id: "connection", title: "General connection",
    icon: "🌱", color: "#7c3aed",
    blurb: "How you connect, communicate and share humour day-to-day.",
    items: [
      "Shared activities / interests",
      "Intellectual / philosophical discussions",
      "Political discussions",
      "Sharing ideas",
      "Sharing humour",
      "Playfulness",
      "Companionship",
      "Understanding",
      "Talking about everyday things",
      "Gift-giving",
    ],
  },
  {
    id: "time-together", title: "Spending time together",
    icon: "⏳", color: "#06b6d4",
    blurb: "Activities, dates, hobbies you'd like to share.",
    items: [
      "Going on dates",
      "Spending time with mutual friends",
      "Concerts, museums, plays",
      "Sports together",
      "Watching movies",
      "Watching TV shows",
      "Playing video games",
      "Reading books",
      "Listening to podcasts / music",
      "Sharing art, music, poetry, memes",
      "Spending time in nature",
      "Eating out",
      "Learning something new together",
      "Co-working",
      "Dancing",
    ],
  },
  {
    id: "creative", title: "Creative together",
    icon: "🎨", color: "#ec4899",
    blurb: "Joint creative endeavours.",
    items: [
      "Visual art", "Craft", "Music", "Photography",
      "Comedy", "Writing / poetry", "Painting / drawing",
      "Dance", "Theatre",
    ],
  },
  {
    id: "social-circles", title: "Mutual social circles",
    icon: "👥", color: "#10b981",
    blurb: "How your social worlds connect.",
    items: [
      "Cultivate mutual circle of friends",
      "Introduce each other to own social group(s)",
      "Introduce each other to family members",
      "Keep social circles separate",
    ],
  },
  {
    id: "collaboration", title: "(Professional) collaboration",
    icon: "🤝", color: "#0ea5e9",
    blurb: "Working on things together.",
    items: [
      "Teaching", "Mutual projects", "Organising events",
      "Activism", "Founding a business",
    ],
  },
  {
    id: "belief", title: "Belief and religion",
    icon: "🕊️", color: "#a78bfa",
    blurb: "Spiritual life and worldview.",
    items: [
      "Shared ritual / prayer",
      "Shared beliefs",
      "Discussions",
      "Shared religious institution(s)",
      "Tolerance for other beliefs",
    ],
  },
  {
    id: "emotional-intimacy", title: "Emotional intimacy",
    icon: "💞", color: "#ef4444",
    blurb: "Vulnerability, openness, trust, conflict.",
    items: [
      "Being vulnerable",
      "Mutual trust",
      "Openness",
      "Finding mutual communication style",
      "Being interested in each other's inner life",
      "Sharing and communicating",
      "Mutual respect",
      "Quarrelling",
      "Calling each other out",
      "Talking about mental health",
      "Constructive criticism",
      "Talking about fears",
      "Radical honesty",
      "Reflecting conflict patterns",
    ],
  },
  {
    id: "physical-intimacy", title: "Physical intimacy",
    icon: "🤗", color: "#f97316",
    blurb: "Non-sexual physical closeness.",
    items: [
      "Dancing", "Cuddles", "Hugs", "Pets", "Massage",
      "Handholding", "Nudity", "Kissing", "Body contact", "Co-sleeping",
    ],
  },
  {
    id: "sexual", title: "Sexual practices and kinks",
    icon: "🔥", color: "#dc2626",
    blurb: "Use G/R/× notation in notes for giving / receiving / both.",
    gr: true,
    items: [
      "Orgasms", "Genital touching", "Oral sex", "Anal stimulation",
      "Vaginal penetration", "Anal penetration",
      "Discovering together", "Virtual sex", "Dom / sub dynamic",
      "Orgasm control", "Bondage", "Role play", "Voyeurism",
      "S/M", "Impact play", "Breath play", "Exhibitionism",
      "Sensation play", "Use of toys together", "Group sex",
      "Swinging", "Playfight", "Erotic massages",
      "Sex-positive events", "Outdoor sex",
      "Watch porn together", "Use dating apps together",
    ],
  },
  {
    id: "caregiving", title: "Caregiving",
    icon: "🩺", color: "#14b8a6",
    blurb: "Mutual care in difficult times.", gr: true,
    items: [
      "Physical care (e.g. sickness)",
      "Emotional care",
      "Reliability",
      "Emergencies",
      "End of life",
      "Support in fear / phobias",
      "Trauma awareness and support",
      "Long-term care (chronic illness, disability)",
      "Support with addiction",
    ],
  },
  {
    id: "emotional-support", title: "Emotional support",
    icon: "🫂", color: "#22c55e",
    blurb: "Showing up for one another.", gr: true,
    items: [
      "Listening",
      "Empathy",
      "Asking for advice",
      "Showing up for each other",
      "Being present at important events",
      "Confidante",
      "Accountability partners / body doubling",
    ],
  },
  {
    id: "romantic", title: "Romantic",
    icon: "💖", color: "#e11d48",
    blurb: "Romance, swooning, affection.",
    items: [
      "Cultivating uniqueness",
      "Emotional attraction",
      "\"Being in love\"",
      "Limerence / swooning",
      "Expressing affection",
      "Verbalising romantic feelings",
    ],
  },
  {
    id: "partnership", title: "Partner & companionship",
    icon: "🪢", color: "#8b5cf6",
    blurb: "Long-term shape and shared life.",
    items: [
      "Shared goals / values",
      "Shared understanding of politics / ethics",
      "Find / keep routines",
      "Commitment",
      "Embrace change in and with each other",
      "Mutual growth",
      "Long-term planning",
      "Be involved in important life decisions",
      "Share lifestyle choices",
      "Embrace differences",
    ],
  },
  {
    id: "exclusivity", title: "Exclusivity",
    icon: "🔐", color: "#475569",
    blurb: "Where exclusivity matters (or doesn't).",
    items: [
      "Sexual",
      "Emotional / romantic",
      "Social",
      "Structural (e.g. nesting)",
      "Flexibility / changeability",
    ],
  },
  {
    id: "legal", title: "Legal",
    icon: "⚖️", color: "#334155",
    blurb: "Formal and legal arrangements.",
    items: [
      "Power of attorney",
      "Marriage",
      "Civil partnership",
      "Business partners",
      "Emergency contact",
      "Inheritance / included in will",
    ],
  },
  {
    id: "financial", title: "Financial",
    icon: "💰", color: "#84cc16",
    blurb: "Money matters.",
    items: [
      "Shared responsibilities",
      "Property",
      "Support in need",
      "Regular payments",
      "Shared accounts",
      "Ethical spending",
      "Expensive lifestyle",
      "Frugal lifestyle",
      "Similar spending habits",
      "Share living costs",
      "Financial security",
      "Shared retirement funds",
      "Separate finances",
    ],
  },
  {
    id: "domestic", title: "Domestic",
    icon: "🏠", color: "#f59e0b",
    blurb: "How a shared home looks (or not).",
    items: [
      "Routines",
      "Chores",
      "Sharing a home",
      "Sharing a sleeping space",
      "Cooking together",
      "Sharing meals",
      "Shared cleanliness preferences",
    ],
  },
  {
    id: "planning", title: "Planning & time management",
    icon: "🗓️", color: "#0891b2",
    blurb: "How time together is organised.",
    items: [
      "Quality time together",
      "Reserved time slots",
      "Regular relationship check-ins",
      "Relationshape interval",
      "Spontaneity",
      "Planning time together in advance",
      "Shared calendar",
    ],
  },
  {
    id: "family-planning", title: "Family planning & contraception",
    icon: "👶", color: "#fb7185", gr: true,
    blurb: "Children, contraception, parenthood.",
    items: [
      "Condom",
      "Other barrier(s)",
      "Hormonal contraception",
      "Implant",
      "Surgical contraception",
      "Cycle tracking / natural",
      "Emergency contraception",
      "No contraception",
      "Abortion",
      "Discuss behaviour with other partners",
      "Become (co-)parents",
      "Have genetically related child(ren)",
      "Adoption",
      "Becoming foster parents",
      "Support each other with children from other partners",
    ],
  },
  {
    id: "sexual-health", title: "Safer sex & sexual health",
    icon: "🛡️", color: "#0d9488",
    blurb: "Testing, protection, safer practices.",
    items: [
      "STI testing",
      "Protected oral sex",
      "Protected anal sex",
      "Protected vaginal sex",
      "Protected sex with other partners",
      "HPV vaccination",
      "PrEP",
    ],
  },
  {
    id: "co-caregivers", title: "Co-caregivers",
    icon: "🌿", color: "#65a30d",
    blurb: "Looking after others together.",
    items: [
      "Plants",
      "Animals",
      "Children",
      "Parents",
      "Other people",
    ],
  },
  {
    id: "holidays", title: "Holidays together",
    icon: "🏝️", color: "#0284c7",
    blurb: "Travel, trips, time off.",
    items: [
      "Time off together",
      "Long weekends",
      "Day trips",
      "Week(s) away",
      "Long-term travel / sabbatical",
      "Just the two of us",
      "With friends",
      "With family",
      "With metamour(s)",
      "Abroad",
      "City trips",
      "Cultural travel",
      "Festival / Retreat",
      "Camping / Nature",
      "Road trip",
      "Beach",
      "Active / Adventure",
      "Wellness",
      "By train",
      "By bike",
      "By car",
      "By plane",
    ],
  },
  {
    id: "labels", title: "Labels",
    icon: "🏷️", color: "#9333ea",
    blurb: "What to call this connection.",
    items: [
      "No label", "Colleague", "Friend", "Partner", "Lover",
      "Affair", "Spouse", "Datemate", "Playpartner", "Flatmate",
      "Nesting Partner", "Sugarmama / Sugardaddy",
    ],
  },
  {
    id: "affection-display", title: "Displays of affection",
    icon: "💌", color: "#db2777",
    blurb: "Public-facing affection.",
    items: [
      "At events", "Around friends", "Around family",
      "At work", "On social media", "In public",
    ],
  },
  {
    id: "communication", title: "Communication frequency",
    icon: "💬", color: "#2563eb",
    blurb: "How often you communicate.",
    items: [
      "In-person", "Phone calls", "Voice messages",
      "Text messages", "Written letters",
    ],
  },
  {
    id: "attachment", title: "Relationship attachment",
    icon: "🪶", color: "#a16207",
    blurb: "Attachment style and security.",
    items: [
      "Non-attachment-oriented",
      "Attachment-oriented",
      "Safe haven",
      "Secure base",
      "Comfort with ambiguity",
    ],
  },
  {
    id: "monogamy-labels", title: "(Non-)monogamy labels",
    icon: "♾️", color: "#be185d",
    blurb: "Relationship structure preferences.",
    items: [
      "Monogamous", "Monogam-ish", "Swinging", "Polyfidelitous",
      "Hierarchical polyamory", "Group relationship",
      "Egalitarian polyamory", "Solo polyamory",
      "Free / honest relationship", "Relationship anarchy",
      "Fluid", "Comet relationship", "Single",
    ],
  },
  {
    id: "other-relationships", title: "Cultivating other relationships",
    icon: "🌌", color: "#7e22ce",
    blurb: "Space for other connections.",
    items: [
      "Dating own gender",
      "Dating other genders",
      "Sexual",
      "Romantic",
      "Attachment-oriented",
      "Non-attachment-oriented",
      "Short-term",
      "Long-term",
      "One-night stands",
      "Kink-focused relationships",
      "Dating mutual friends / acquaintances",
      "Solo use of dating apps",
      "Check-in about new relationships before entering",
      "Discuss space for different relationships",
      "Reflect on jealousy together",
      "Veto power",
      "Hierarchical structures",
    ],
  },
  {
    id: "communication-meta", title: "Communication about other relationships",
    icon: "🔁", color: "#9333ea",
    blurb: "How information about other connections is shared.",
    items: [
      "Don't ask, don't tell",
      "Casually keep up to date",
      "Share intimate details",
      "Share details with metamours",
      "Share experiences of being close (e.g. pictures of kissing)",
    ],
  },
  {
    id: "metamours", title: "Contact with metamours",
    icon: "🫧", color: "#0369a1",
    blurb: "Relationship with partner's partners.",
    items: [
      "Casual irregular meetings",
      "Regular meetings",
      "Cultivate getting along",
      "Cultivate friendship between metamours",
      "Kitchen table polyamory",
      "Intimate interactions between metamours",
      "Meeting in public spaces as a polycule",
      "Introduce metamour(s) to own social circle",
    ],
  },
];

// Optional onboarding: a few coarse yes/no themes that map to category ids.
// "include" means: if user says No, those categories are excluded by default
// (user can always re-enable individual ones in the map settings).
export const ONBOARDING_THEMES = [
  {
    id: "physical",
    title: "Physical & sexual",
    blurb: "Includes physical closeness, sexual practices, family planning, sexual health.",
    categories: ["physical-intimacy", "sexual", "family-planning", "sexual-health"],
    defaultOn: true,
  },
  {
    id: "polyamory",
    title: "Polyamory & non-monogamy",
    blurb: "Includes exclusivity, monogamy labels, other relationships, metamours.",
    categories: ["exclusivity", "monogamy-labels", "other-relationships", "communication-meta", "metamours"],
    defaultOn: true,
  },
  {
    id: "household",
    title: "Shared household & domestic life",
    blurb: "Includes domestic chores, financial life, holidays, caregiving for plants/pets/kids.",
    categories: ["domestic", "financial", "co-caregivers", "holidays"],
    defaultOn: true,
  },
  {
    id: "legal-long-term",
    title: "Legal & long-term commitments",
    blurb: "Includes marriage, civil partnership, power of attorney, inheritance.",
    categories: ["legal"],
    defaultOn: true,
  },
  {
    id: "belief",
    title: "Belief & spirituality",
    blurb: "Includes religion, ritual, shared beliefs.",
    categories: ["belief"],
    defaultOn: false,
  },
  {
    id: "collab",
    title: "Professional collaboration",
    blurb: "Includes teaching, mutual projects, activism, founding things together.",
    categories: ["collaboration"],
    defaultOn: false,
  },
];

// Sub-set chosen for the Spider Chart (10–12 axes for readability).
export const SPIDER_AXES = [
  "emotional-intimacy",
  "physical-intimacy",
  "sexual",
  "romantic",
  "partnership",
  "domestic",
  "financial",
  "communication",
  "time-together",
  "caregiving",
  "exclusivity",
  "other-relationships",
];

// Format constants used for shareable, encrypted exports.
export const FILE_FORMAT = {
  magic: "RSHAPE1",
  version: 1,
};
