// Relationshapes questionnaire data model.
// Source: Relationshapes Pre-Release 1 (Anne Lüscher, Benjamin Frey, 2025)
// Licensed CC BY-NC 4.0. Adapted for app use.

// Default scale, lowest disagreement first, strongest agreement last.
// Numeric values are derived from position automatically.
// Users can customise labels / colours / step count via Map settings.
export const DEFAULT_SCALE = [
  { key: "no",         label: "No",            short: "No",         value: 0, color: "#264653", description: "I do not want / agree to this." },
  { key: "not-really", label: "Not really",    short: "Not really", value: 1, color: "#577590", description: "I lean against this." },
  { key: "maybe",      label: "Maybe / future",short: "Maybe",      value: 2, color: "#43aa8b", description: "Hopefully or maybe in the future." },
  { key: "open",       label: "Open to it",    short: "Open",       value: 3, color: "#90be6d", description: "I am open, neutral, willing to explore." },
  { key: "want",       label: "Want / like",   short: "Want",       value: 4, color: "#f9c74f", description: "I would like this." },
  { key: "hell-yes",   label: "Hell, yes!",    short: "Hell yes",   value: 5, color: "#f3722c", description: "Strong yes, exciting and welcome." },
  { key: "need",       label: "Need",          short: "Need",       value: 6, color: "#e63946", description: "Highest importance. If unmet I may reconsider the relationship." },
];

// Tag GR = item supports giving/receiving notation.
// Categories trimmed slightly for app use; users can add custom items in profile.
export const CATEGORIES = [
  {
    id: "connection", title: "General connection", de: "Allgemeine Verbindung",
    icon: "🌱", color: "#7c3aed",
    blurb: "How you connect, communicate and share humour day-to-day.",
    deBlurb: "Wie ihr euch verbindet, kommuniziert und Humor teilt.",
    items: [
      "Shared activities / interests",
      "Intellectual / philosophical discussions",
      "Political discussions",
      "Sharing ideas",
      "Sharing humour",
      "Playfulness",
      "Companionship",
      "Understanding",
      "Talking about everyday things",
      "Gift-giving",
    ],
    deItems: [
      "Gemeinsame Aktivitäten / Interessen",
      "Intellektuelle / philosophische Gespräche",
      "Politische Gespräche",
      "Ideen teilen",
      "Humor teilen",
      "Verspieltheit",
      "Gesellschaft",
      "Verständnis",
      "Über den Alltag reden",
      "Geschenke machen",
    ],
  },
  {
    id: "time-together", title: "Spending time together", de: "Zeit miteinander verbringen",
    icon: "⏳", color: "#06b6d4",
    blurb: "Activities, dates, hobbies you'd like to share.",
    deBlurb: "Aktivitäten, Verabredungen und Hobbys, die ihr gerne teilt.",
    items: [
      "Going on dates",
      "Spending time with mutual friends",
      "Concerts, museums, plays",
      "Sports together",
      "Watching movies",
      "Watching TV shows",
      "Playing video games",
      "Reading books",
      "Listening to podcasts / music",
      "Sharing art, music, poetry, memes",
      "Spending time in nature",
      "Eating out",
      "Learning something new together",
      "Co-working",
      "Dancing",
    ],
    deItems: [
      "Verabredungen",
      "Zeit mit gemeinsamen Freund*innen",
      "Konzerte, Museen, Theater",
      "Sport gemeinsam",
      "Filme schauen",
      "Serien schauen",
      "Videospiele spielen",
      "Bücher lesen",
      "Podcasts / Musik hören",
      "Kunst, Musik, Gedichte, Memes teilen",
      "Zeit in der Natur verbringen",
      "Essen gehen",
      "Gemeinsam Neues lernen",
      "Co-Working",
      "Tanzen",
    ],
  },
  {
    id: "creative", title: "Creative together", de: "Kreativ sein zusammen",
    icon: "🎨", color: "#ec4899",
    blurb: "Joint creative endeavours.",
    deBlurb: "Gemeinsame kreative Projekte.",
    items: [
      "Visual art", "Craft", "Music", "Photography",
      "Comedy", "Writing / poetry", "Painting / drawing",
      "Dance", "Theatre",
    ],
    deItems: [
      "Bildende Kunst", "Handwerk", "Musik", "Fotografie",
      "Comedy", "Schreiben / Lyrik", "Malen / Zeichnen",
      "Tanz", "Theater",
    ],
  },
  {
    id: "social-circles", title: "Mutual social circles", de: "Gemeinsame Freundeskreise",
    icon: "👥", color: "#10b981",
    blurb: "How your social worlds connect.",
    deBlurb: "Wie eure sozialen Welten sich verbinden.",
    items: [
      "Cultivate mutual circle of friends",
      "Introduce each other to own social group(s)",
      "Introduce each other to family members",
      "Keep social circles separate",
    ],
    deItems: [
      "Gemeinsamen Freundeskreis pflegen",
      "Sich gegenseitig den eigenen Freundeskreisen vorstellen",
      "Sich gegenseitig der Familie vorstellen",
      "Freundeskreise getrennt halten",
    ],
  },
  {
    id: "collaboration", title: "(Professional) collaboration", de: "Zusammenarbeit / Gemeinsame Projekte",
    icon: "🤝", color: "#0ea5e9",
    blurb: "Working on things together.",
    deBlurb: "Gemeinsam an Projekten arbeiten.",
    items: [
      "Teaching", "Mutual projects", "Organising events",
      "Activism", "Founding a business",
    ],
    deItems: [
      "Unterrichten / Lehren", "Gemeinsame Projekte", "Events organisieren",
      "Aktivismus", "Unternehmen gründen",
    ],
  },
  {
    id: "belief", title: "Belief and religion", de: "Glaube und Religion",
    icon: "🕊️", color: "#a78bfa",
    blurb: "Spiritual life and worldview.",
    deBlurb: "Spirituelles Leben und Weltanschauung.",
    items: [
      "Shared ritual / prayer",
      "Shared beliefs",
      "Discussions",
      "Shared religious institution(s)",
      "Tolerance for other beliefs",
    ],
    deItems: [
      "Gemeinsames Ritual / Gebet",
      "Geteilte Überzeugungen",
      "Gespräche",
      "Gemeinsame Religionsgemeinschaft(en)",
      "Toleranz gegenüber anderen Glaubensrichtungen",
    ],
  },
  {
    id: "emotional-intimacy", title: "Emotional intimacy", de: "Emotionale Intimität",
    icon: "💞", color: "#ef4444",
    blurb: "Vulnerability, openness, trust, conflict.",
    deBlurb: "Verletzlichkeit, Offenheit, Vertrauen, Konflikt.",
    items: [
      "Being vulnerable",
      "Mutual trust",
      "Openness",
      "Finding mutual communication style",
      "Being interested in each other's inner life",
      "Sharing and communicating",
      "Mutual respect",
      "Quarrelling",
      "Calling each other out",
      "Talking about mental health",
      "Constructive criticism",
      "Talking about fears",
      "Radical honesty",
      "Reflecting conflict patterns",
    ],
    deItems: [
      "Verletzlichkeit zeigen",
      "Gegenseitiges Vertrauen",
      "Offenheit",
      "Gemeinsamen Kommunikationsstil finden",
      "Interesse am inneren Leben des anderen",
      "Teilen und kommunizieren",
      "Gegenseitiger Respekt",
      "Streiten",
      "Sich gegenseitig konfrontieren",
      "Über psychische Gesundheit sprechen",
      "Konstruktive Kritik",
      "Über Ängste sprechen",
      "Radikale Ehrlichkeit",
      "Konfliktmuster reflektieren",
    ],
  },
  {
    id: "physical-intimacy", title: "Physical intimacy", de: "Körperliche Intimität",
    icon: "🤗", color: "#f97316",
    blurb: "Non-sexual physical closeness.",
    deBlurb: "Nicht-sexuelle körperliche Nähe.",
    items: [
      "Dancing", "Cuddles", "Hugs", "Pets", "Massage",
      "Handholding", "Nudity", "Kissing", "Body contact", "Co-sleeping",
    ],
    deItems: [
      "Tanzen", "Kuscheln", "Umarmungen", "Streicheln", "Massage",
      "Händchen halten", "Nacktheit", "Küssen", "Körperkontakt", "Zusammen schlafen",
    ],
  },
  {
    id: "sexual", title: "Sexual practices and kinks", de: "Sexuelle Praktiken und Kinks",
    icon: "🔥", color: "#dc2626",
    blurb: "Rate each item for Giving and Receiving separately.",
    deBlurb: "Geben und Empfangen bitte separat bewerten.",
    gr: true,
    items: [
      "Orgasms", "Genital touching", "Oral sex", "Anal stimulation",
      "Vaginal penetration", "Anal penetration",
      "Discovering together", "Virtual sex", "Dom / sub dynamic",
      "Orgasm control", "Bondage", "Role play", "Voyeurism",
      "S/M", "Impact play", "Breath play", "Exhibitionism",
      "Sensation play", "Use of toys together", "Group sex",
      "Swinging", "Playfight", "Erotic massages",
      "Sex-positive events", "Outdoor sex",
      "Watch porn together", "Use dating apps together",
    ],
    deItems: [
      "Orgasmen", "Genitale Berührung", "Oralsex", "Anale Stimulation",
      "Vaginale Penetration", "Anale Penetration",
      "Gemeinsam erkunden", "Virtueller Sex", "Dom / Sub Dynamik",
      "Orgasmuskontrolle", "Bondage", "Rollenspiel", "Voyeurismus",
      "S/M", "Impact Play", "Breath Play", "Exhibitionismus",
      "Sensation Play", "Spielzeug gemeinsam nutzen", "Gruppensex",
      "Swingen", "Playfight", "Erotische Massagen",
      "Sex-positive Veranstaltungen", "Sex im Freien",
      "Gemeinsam Pornos schauen", "Dating-Apps gemeinsam nutzen",
    ],
  },
  {
    id: "caregiving", title: "Caregiving", de: "Fürsorge",
    icon: "🩺", color: "#14b8a6",
    blurb: "Mutual care in difficult times.", gr: true,
    deBlurb: "Gegenseitige Fürsorge in schwierigen Zeiten.",
    items: [
      "Physical care (e.g. sickness)",
      "Emotional care",
      "Reliability",
      "Emergencies",
      "End of life",
      "Support in fear / phobias",
      "Trauma awareness and support",
      "Long-term care (chronic illness, disability)",
      "Support with addiction",
    ],
    deItems: [
      "Körperliche Fürsorge (z.B. Krankheit)",
      "Emotionale Fürsorge",
      "Verlässlichkeit",
      "Notfälle",
      "Lebensende",
      "Unterstützung bei Angst / Phobien",
      "Trauma-Bewusstsein und Unterstützung",
      "Langzeitpflege (chron. Krankheit, Behinderung)",
      "Unterstützung bei Sucht",
    ],
  },
  {
    id: "emotional-support", title: "Emotional support", de: "Emotionale Unterstützung",
    icon: "🫂", color: "#22c55e",
    blurb: "Showing up for one another.", gr: true,
    deBlurb: "Füreinander da sein.",
    items: [
      "Listening",
      "Empathy",
      "Asking for advice",
      "Showing up for each other",
      "Being present at important events",
      "Confidante",
      "Accountability partners / body doubling",
    ],
    deItems: [
      "Zuhören",
      "Empathie",
      "Um Rat fragen",
      "Füreinander da sein",
      "Bei wichtigen Ereignissen präsent sein",
      "Vertrauensperson",
      "Accountability-Partner*in / Body Doubling",
    ],
  },
  {
    id: "romantic", title: "Romantic", de: "Romantik",
    icon: "💖", color: "#e11d48",
    blurb: "Romance, swooning, affection.",
    deBlurb: "Romantik, Schwärmen, Zuneigung.",
    items: [
      "Cultivating uniqueness",
      "Emotional attraction",
      "\"Being in love\"",
      "Limerence / swooning",
      "Expressing affection",
      "Verbalising romantic feelings",
    ],
    deItems: [
      "Einzigartigkeit pflegen",
      "Emotionale Anziehung",
      "\"Verliebt sein\"",
      "Verknalltsein / Schwärmen",
      "Zuneigung ausdrücken",
      "Romantische Gefühle aussprechen",
    ],
  },
  {
    id: "partnership", title: "Partner & companionship", de: "Partner & Begleitung",
    icon: "🪢", color: "#8b5cf6",
    blurb: "Long-term shape and shared life.",
    deBlurb: "Langfristige Ausrichtung und gemeinsames Leben.",
    items: [
      "Shared goals / values",
      "Shared understanding of politics / ethics",
      "Find / keep routines",
      "Commitment",
      "Embrace change in and with each other",
      "Mutual growth",
      "Long-term planning",
      "Be involved in important life decisions",
      "Share lifestyle choices",
      "Embrace differences",
    ],
    deItems: [
      "Gemeinsame Ziele / Werte",
      "Gemeinsames Verständnis von Politik / Ethik",
      "Routinen finden / beibehalten",
      "Verbindlichkeit",
      "Veränderungen aneinander annehmen",
      "Gegenseitiges Wachstum",
      "Langfristige Planung",
      "An wichtigen Lebensentscheidungen beteiligt sein",
      "Lebensstil-Entscheidungen teilen",
      "Unterschiede akzeptieren",
    ],
  },
  {
    id: "exclusivity", title: "Exclusivity", de: "Exklusivität",
    icon: "🔐", color: "#475569",
    blurb: "Where exclusivity matters (or doesn't).",
    deBlurb: "Wo Exklusivität wichtig ist (oder nicht).",
    items: [
      "Sexual",
      "Emotional / romantic",
      "Social",
      "Structural (e.g. nesting)",
      "Flexibility / changeability",
    ],
    deItems: [
      "Sexuell",
      "Emotional / romantisch",
      "Sozial",
      "Strukturell (z.B. Nesting)",
      "Flexibilität / Veränderbarkeit",
    ],
  },
  {
    id: "legal", title: "Legal", de: "Rechtliches",
    icon: "⚖️", color: "#334155",
    blurb: "Formal and legal arrangements.",
    deBlurb: "Formale und rechtliche Vereinbarungen.",
    items: [
      "Power of attorney",
      "Marriage",
      "Civil partnership",
      "Business partners",
      "Emergency contact",
      "Inheritance / included in will",
    ],
    deItems: [
      "Vollmacht",
      "Ehe",
      "Eingetragene Partnerschaft",
      "Geschäftspartner",
      "Notfallkontakt",
      "Erbschaft / Im Testament berücksichtigt",
    ],
  },
  {
    id: "financial", title: "Financial", de: "Finanzen",
    icon: "💰", color: "#84cc16",
    blurb: "Money matters.",
    deBlurb: "Finanzielle Themen.",
    items: [
      "Shared responsibilities",
      "Property",
      "Support in need",
      "Regular payments",
      "Shared accounts",
      "Ethical spending",
      "Expensive lifestyle",
      "Frugal lifestyle",
      "Similar spending habits",
      "Share living costs",
      "Financial security",
      "Shared retirement funds",
      "Separate finances",
    ],
    deItems: [
      "Geteilte Verantwortung",
      "Eigentum",
      "Unterstützung in der Not",
      "Regelmäßige Zahlungen",
      "Gemeinsame Konten",
      "Ethisches Konsumverhalten",
      "Teurer Lebensstil",
      "Sparsamer Lebensstil",
      "Ähnliche Ausgabegewohnheiten",
      "Lebenskosten teilen",
      "Finanzielle Sicherheit",
      "Gemeinsame Altersvorsorge",
      "Getrennte Finanzen",
    ],
  },
  {
    id: "domestic", title: "Domestic", de: "Haushalt",
    icon: "🏠", color: "#f59e0b",
    blurb: "How a shared home looks (or not).",
    deBlurb: "Wie ein gemeinsamer Haushalt aussieht (oder nicht).",
    items: [
      "Routines",
      "Chores",
      "Sharing a home",
      "Sharing a sleeping space",
      "Cooking together",
      "Sharing meals",
      "Shared cleanliness preferences",
    ],
    deItems: [
      "Routinen",
      "Haushaltsaufgaben",
      "Gemeinsame Wohnung",
      "Gemeinsamer Schlafbereich",
      "Gemeinsam kochen",
      "Gemeinsame Mahlzeiten",
      "Geteilte Sauberkeitsvorstellungen",
    ],
  },
  {
    id: "planning", title: "Planning & time management", de: "Planung & Zeitmanagement",
    icon: "🗓️", color: "#0891b2",
    blurb: "How time together is organised.",
    deBlurb: "Wie gemeinsame Zeit organisiert wird.",
    items: [
      "Quality time together",
      "Reserved time slots",
      "Regular relationship check-ins",
      "Relationshapes interval",
      "Spontaneity",
      "Planning time together in advance",
      "Shared calendar",
    ],
    deItems: [
      "Qualitätszeit miteinander",
      "Feste Zeitslots",
      "Regelmäßige Beziehungsgespräche",
      "Relationshapes-Intervall",
      "Spontanität",
      "Gemeinsame Zeit im Voraus planen",
      "Gemeinsamer Kalender",
    ],
  },
  {
    id: "family-planning", title: "Family planning & contraception", de: "Familienplanung & Verhütung",
    icon: "👶", color: "#fb7185", gr: true,
    blurb: "Children, contraception, parenthood.",
    deBlurb: "Kinder, Verhütung, Elternschaft.",
    items: [
      "Condom",
      "Other barrier(s)",
      "Hormonal contraception",
      "Implant",
      "Surgical contraception",
      "Cycle tracking / natural",
      "Emergency contraception",
      "No contraception",
      "Abortion",
      "Discuss behaviour with other partners",
      "Become (co-)parents",
      "Have genetically related child(ren)",
      "Adoption",
      "Becoming foster parents",
      "Support each other with children from other partners",
    ],
    deItems: [
      "Kondom",
      "Andere Barrieremethode(n)",
      "Hormonelle Verhütung",
      "Implantat",
      "Chirurgische Verhütung",
      "Zyklusverfolgung / Natürliche Methode",
      "Notfallverhütung",
      "Keine Verhütung",
      "Schwangerschaftsabbruch",
      "Verhalten mit anderen Partner*innen besprechen",
      "(Mit-)Eltern werden",
      "Genetisch verwandte Kinder haben",
      "Adoption",
      "Pflegeeltern werden",
      "Sich gegenseitig mit Kindern aus anderen Beziehungen unterstützen",
    ],
  },
  {
    id: "sexual-health", title: "Safer sex & sexual health", de: "Safer Sex & sexuelle Gesundheit",
    icon: "🛡️", color: "#0d9488",
    blurb: "Testing, protection, safer practices.",
    deBlurb: "Tests, Schutz und sichere Praktiken.",
    items: [
      "STI testing",
      "Protected oral sex",
      "Protected anal sex",
      "Protected vaginal sex",
      "Protected sex with other partners",
      "HPV vaccination",
      "PrEP",
    ],
    deItems: [
      "STI-Tests",
      "Geschützter Oralsex",
      "Geschützter Analsex",
      "Geschützter Vaginalsex",
      "Geschützter Sex mit anderen Partner*innen",
      "HPV-Impfung",
      "PrEP",
    ],
  },
  {
    id: "co-caregivers", title: "Co-caregivers", de: "Gemeinsame Betreuung",
    icon: "🌿", color: "#65a30d",
    blurb: "Looking after others together.",
    deBlurb: "Gemeinsam für andere sorgen.",
    items: [
      "Plants",
      "Animals",
      "Children",
      "Parents",
      "Other people",
    ],
    deItems: [
      "Pflanzen",
      "Tiere",
      "Kinder",
      "Eltern",
      "Andere Menschen",
    ],
  },
  {
    id: "holidays", title: "Holidays together", de: "Gemeinsame Ferien",
    icon: "🏝️", color: "#0284c7",
    blurb: "Travel, trips, time off.",
    deBlurb: "Reisen, Ausflüge, Auszeiten.",
    items: [
      "Time off together",
      "Long weekends",
      "Day trips",
      "Week(s) away",
      "Long-term travel / sabbatical",
      "Just the two of us",
      "With friends",
      "With family",
      "With metamour(s)",
      "Abroad",
      "City trips",
      "Cultural travel",
      "Festival / Retreat",
      "Camping / Nature",
      "Road trip",
      "Beach",
      "Active / Adventure",
      "Wellness",
      "By train",
      "By bike",
      "By car",
      "By plane",
    ],
    deItems: [
      "Gemeinsame Auszeit",
      "Verlängerte Wochenenden",
      "Tagesausflüge",
      "Woche(n) verreisen",
      "Längere Reisen / Sabbatical",
      "Nur wir zwei",
      "Mit Freund*innen",
      "Mit Familie",
      "Mit Metamour(s)",
      "Im Ausland",
      "Städtetrips",
      "Kulturreisen",
      "Festival / Retreat",
      "Camping / Natur",
      "Roadtrip",
      "Strand",
      "Aktiv / Abenteuer",
      "Wellness",
      "Mit dem Zug",
      "Mit dem Rad",
      "Mit dem Auto",
      "Mit dem Flugzeug",
    ],
  },
  {
    id: "labels", title: "Labels", de: "Bezeichnungen",
    icon: "🏷️", color: "#9333ea",
    blurb: "What to call this connection.",
    deBlurb: "Wie ihr diese Verbindung nennt.",
    items: [
      "No label", "Colleague", "Friend", "Partner", "Lover",
      "Affair", "Spouse", "Datemate", "Playpartner", "Flatmate",
      "Nesting Partner", "Sugarmama / Sugardaddy",
    ],
    deItems: [
      "Keine Bezeichnung", "Kolleg*in", "Freund*in", "Partner*in", "Liebhaber*in",
      "Affäre", "Ehepartner*in", "Datemate", "Spielpartner*in", "Mitbewohner*in",
      "Nesting-Partner*in", "Sugarmama / Sugardaddy",
    ],
  },
  {
    id: "affection-display", title: "Displays of affection", de: "Zuneigung zeigen",
    icon: "💌", color: "#db2777",
    blurb: "Public-facing affection.",
    deBlurb: "Zuneigung nach außen zeigen.",
    items: [
      "At events", "Around friends", "Around family",
      "At work", "On social media", "In public",
    ],
    deItems: [
      "Bei Veranstaltungen", "Im Freundeskreis", "In der Familie",
      "Bei der Arbeit", "In sozialen Medien", "In der Öffentlichkeit",
    ],
  },
  {
    id: "communication", title: "Communication frequency", de: "Kommunikations­häufigkeit",
    icon: "💬", color: "#2563eb",
    blurb: "How often you communicate.",
    deBlurb: "Wie oft ihr kommuniziert.",
    items: [
      "In-person", "Phone calls", "Voice messages",
      "Text messages", "Written letters",
    ],
    deItems: [
      "Persönlich", "Telefonate", "Sprachnachrichten",
      "Textnachrichten", "Briefe",
    ],
  },
  {
    id: "attachment", title: "Relationship attachment", de: "Beziehungsbindung",
    icon: "🪶", color: "#a16207",
    blurb: "Attachment style and security.",
    deBlurb: "Bindungsstil und Sicherheit.",
    items: [
      "Non-attachment-oriented",
      "Attachment-oriented",
      "Safe haven",
      "Secure base",
      "Comfort with ambiguity",
    ],
    deItems: [
      "Nicht bindungsorientiert",
      "Bindungsorientiert",
      "Sicherer Hafen",
      "Sichere Basis",
      "Komfort mit Ambiguität",
    ],
  },
  {
    id: "monogamy-labels", title: "(Non-)monogamy labels", de: "(Nicht-)Monogamie-Bezeichnungen",
    icon: "♾️", color: "#be185d",
    blurb: "Relationship structure preferences.",
    deBlurb: "Beziehungsstruktur-Präferenzen.",
    items: [
      "Monogamous", "Monogam-ish", "Swinging", "Polyfidelitous",
      "Hierarchical polyamory", "Group relationship",
      "Egalitarian polyamory", "Solo polyamory",
      "Free / honest relationship", "Relationship anarchy",
      "Fluid", "Comet relationship", "Single",
    ],
    deItems: [
      "Monogam", "Mono-ish", "Swingen", "Polyfiditös",
      "Hierarchische Polyamorie", "Gruppenbeziehung",
      "Egalitäre Polyamorie", "Solo-Polyamorie",
      "Freie / ehrliche Beziehung", "Beziehungsanarchie",
      "Fluid", "Kometenbeziehung", "Single",
    ],
  },
  {
    id: "other-relationships", title: "Cultivating other relationships", de: "Andere Beziehungen pflegen",
    icon: "🌌", color: "#7e22ce",
    blurb: "Space for other connections.",
    deBlurb: "Raum für andere Verbindungen.",
    items: [
      "Dating own gender",
      "Dating other genders",
      "Sexual",
      "Romantic",
      "Attachment-oriented",
      "Non-attachment-oriented",
      "Short-term",
      "Long-term",
      "One-night stands",
      "Kink-focused relationships",
      "Dating mutual friends / acquaintances",
      "Solo use of dating apps",
      "Check-in about new relationships before entering",
      "Discuss space for different relationships",
      "Reflect on jealousy together",
      "Veto power",
      "Hierarchical structures",
    ],
    deItems: [
      "Eigenes Geschlecht daten",
      "Andere Geschlechter daten",
      "Sexuell",
      "Romantisch",
      "Bindungsorientiert",
      "Nicht bindungsorientiert",
      "Kurzfristig",
      "Langfristig",
      "One-Night-Stands",
      "Kink-fokussierte Beziehungen",
      "Gemeinsame Freund*innen / Bekannte daten",
      "Alleinige Nutzung von Dating-Apps",
      "Vor neuen Beziehungen einchecken",
      "Raum für verschiedene Beziehungen besprechen",
      "Gemeinsam über Eifersucht reflektieren",
      "Vetorecht",
      "Hierarchische Strukturen",
    ],
  },
  {
    id: "communication-meta", title: "Communication about other relationships", de: "Kommunikation über andere Beziehungen",
    icon: "🔁", color: "#9333ea",
    blurb: "How information about other connections is shared.",
    deBlurb: "Wie Informationen über andere Verbindungen geteilt werden.",
    items: [
      "Don't ask, don't tell",
      "Casually keep up to date",
      "Share intimate details",
      "Share details with metamours",
      "Share experiences of being close (e.g. pictures of kissing)",
    ],
    deItems: [
      "Nicht fragen, nicht erzählen",
      "Locker auf dem Laufenden halten",
      "Intime Details teilen",
      "Details mit Metamours teilen",
      "Nähe-Erlebnisse teilen (z.B. Kuss-Fotos)",
    ],
  },
  {
    id: "metamours", title: "Contact with metamours", de: "Kontakt mit Metamours",
    icon: "🫧", color: "#0369a1",
    blurb: "Relationship with partner's partners.",
    deBlurb: "Beziehung zu den Partner*innen deiner Partner*innen.",
    items: [
      "Casual irregular meetings",
      "Regular meetings",
      "Cultivate getting along",
      "Cultivate friendship between metamours",
      "Kitchen table polyamory",
      "Intimate interactions between metamours",
      "Meeting in public spaces as a polycule",
      "Introduce metamour(s) to own social circle",
    ],
    deItems: [
      "Gelegentliche, unregelmäßige Treffen",
      "Regelmäßige Treffen",
      "Miteinander auskommen pflegen",
      "Freundschaft zwischen Metamours pflegen",
      "Küchentisch-Polyamorie",
      "Intime Interaktionen zwischen Metamours",
      "Als Polycule in der Öffentlichkeit treffen",
      "Metamour(s) dem eigenen Freundeskreis vorstellen",
    ],
  },
];

// Category groups for the onboarding picker.
// Each group has EN + DE titles; categories lists the category ids in display order.
// defaultOn controls which categories are pre-checked when starting a new map.
export const CATEGORY_GROUPS = [
  {
    id: "general",
    en: "General", de: "Allgemein",
    categories: [
      { id: "connection",        defaultOn: true },
      { id: "time-together",     defaultOn: true },
      { id: "communication",     defaultOn: true },
      { id: "planning",          defaultOn: true },
      { id: "holidays",          defaultOn: true },
      { id: "social-circles",    defaultOn: true },
      { id: "partnership",       defaultOn: true },
      { id: "emotional-intimacy",defaultOn: true },
    ],
  },
  {
    id: "collab",
    en: "Collaboration & shared practices", de: "Zusammenarbeit & gemeinsame Praktiken",
    categories: [
      { id: "collaboration", defaultOn: false },
      { id: "creative",      defaultOn: true },
      { id: "belief",        defaultOn: false },
    ],
  },
  {
    id: "structure",
    en: "Relationship structure", de: "Beziehungsstruktur",
    categories: [
      { id: "romantic",             defaultOn: true },
      { id: "exclusivity",          defaultOn: true },
      { id: "labels",               defaultOn: true },
      { id: "attachment",           defaultOn: true },
      { id: "monogamy-labels",      defaultOn: true },
      { id: "metamours",            defaultOn: true },
      { id: "communication-meta",   defaultOn: true },
      { id: "other-relationships",  defaultOn: true },
    ],
  },
  {
    id: "physical",
    en: "Physical & sexual", de: "Körperlich & sexuell",
    categories: [
      { id: "physical-intimacy",  defaultOn: true },
      { id: "sexual",             defaultOn: true },
      { id: "affection-display",  defaultOn: true },
      { id: "sexual-health",      defaultOn: true },
      { id: "family-planning",    defaultOn: true },
    ],
  },
  {
    id: "care",
    en: "Responsibilities & care", de: "Verantwortung & Fürsorge",
    categories: [
      { id: "financial",       defaultOn: true },
      { id: "domestic",        defaultOn: true },
      { id: "legal",           defaultOn: true },
      { id: "co-caregivers",   defaultOn: true },
      { id: "caregiving",      defaultOn: true },
      { id: "emotional-support", defaultOn: true },
    ],
  },
];

// Sub-set chosen for the Spider Chart (10–12 axes for readability).
export const SPIDER_AXES = [
  "emotional-intimacy",
  "physical-intimacy",
  "sexual",
  "romantic",
  "partnership",
  "domestic",
  "financial",
  "communication",
  "time-together",
  "caregiving",
  "exclusivity",
  "other-relationships",
];

// Format constants used for shareable, encrypted exports.
export const FILE_FORMAT = {
  magic: "RSHAPE1",
  version: 1,
};
